// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fmsmoov.proto

#include "fmsmoov.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace fmsmoov {
constexpr ProcessorLiveData::ProcessorLiveData(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : inl_(0)
  , inr_(0)
  , outl_(0)
  , outr_(0){}
struct ProcessorLiveDataDefaultTypeInternal {
  constexpr ProcessorLiveDataDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ProcessorLiveDataDefaultTypeInternal() {}
  union {
    ProcessorLiveData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ProcessorLiveDataDefaultTypeInternal _ProcessorLiveData_default_instance_;
}  // namespace fmsmoov
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_fmsmoov_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_fmsmoov_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_fmsmoov_2eproto = nullptr;

const uint32_t TableStruct_fmsmoov_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fmsmoov::ProcessorLiveData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::fmsmoov::ProcessorLiveData, inl_),
  PROTOBUF_FIELD_OFFSET(::fmsmoov::ProcessorLiveData, inr_),
  PROTOBUF_FIELD_OFFSET(::fmsmoov::ProcessorLiveData, outl_),
  PROTOBUF_FIELD_OFFSET(::fmsmoov::ProcessorLiveData, outr_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::fmsmoov::ProcessorLiveData)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fmsmoov::_ProcessorLiveData_default_instance_),
};

const char descriptor_table_protodef_fmsmoov_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rfmsmoov.proto\022\007fmsmoov\"I\n\021ProcessorLiv"
  "eData\022\013\n\003inL\030\001 \001(\002\022\013\n\003inR\030\002 \001(\002\022\014\n\004outL\030"
  "\003 \001(\002\022\014\n\004outR\030\004 \001(\002b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_fmsmoov_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_fmsmoov_2eproto = {
  false, false, 107, descriptor_table_protodef_fmsmoov_2eproto, "fmsmoov.proto", 
  &descriptor_table_fmsmoov_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_fmsmoov_2eproto::offsets,
  file_level_metadata_fmsmoov_2eproto, file_level_enum_descriptors_fmsmoov_2eproto, file_level_service_descriptors_fmsmoov_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_fmsmoov_2eproto_getter() {
  return &descriptor_table_fmsmoov_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_fmsmoov_2eproto(&descriptor_table_fmsmoov_2eproto);
namespace fmsmoov {

// ===================================================================

class ProcessorLiveData::_Internal {
 public:
};

ProcessorLiveData::ProcessorLiveData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:fmsmoov.ProcessorLiveData)
}
ProcessorLiveData::ProcessorLiveData(const ProcessorLiveData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&inl_, &from.inl_,
    static_cast<size_t>(reinterpret_cast<char*>(&outr_) -
    reinterpret_cast<char*>(&inl_)) + sizeof(outr_));
  // @@protoc_insertion_point(copy_constructor:fmsmoov.ProcessorLiveData)
}

inline void ProcessorLiveData::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&inl_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&outr_) -
    reinterpret_cast<char*>(&inl_)) + sizeof(outr_));
}

ProcessorLiveData::~ProcessorLiveData() {
  // @@protoc_insertion_point(destructor:fmsmoov.ProcessorLiveData)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ProcessorLiveData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ProcessorLiveData::ArenaDtor(void* object) {
  ProcessorLiveData* _this = reinterpret_cast< ProcessorLiveData* >(object);
  (void)_this;
}
void ProcessorLiveData::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ProcessorLiveData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ProcessorLiveData::Clear() {
// @@protoc_insertion_point(message_clear_start:fmsmoov.ProcessorLiveData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&inl_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&outr_) -
      reinterpret_cast<char*>(&inl_)) + sizeof(outr_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProcessorLiveData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float inL = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          inl_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float inR = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          inr_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float outL = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          outl_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float outR = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          outr_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProcessorLiveData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fmsmoov.ProcessorLiveData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float inL = 1;
  if (!(this->_internal_inl() <= 0 && this->_internal_inl() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_inl(), target);
  }

  // float inR = 2;
  if (!(this->_internal_inr() <= 0 && this->_internal_inr() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_inr(), target);
  }

  // float outL = 3;
  if (!(this->_internal_outl() <= 0 && this->_internal_outl() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_outl(), target);
  }

  // float outR = 4;
  if (!(this->_internal_outr() <= 0 && this->_internal_outr() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_outr(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fmsmoov.ProcessorLiveData)
  return target;
}

size_t ProcessorLiveData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fmsmoov.ProcessorLiveData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float inL = 1;
  if (!(this->_internal_inl() <= 0 && this->_internal_inl() >= 0)) {
    total_size += 1 + 4;
  }

  // float inR = 2;
  if (!(this->_internal_inr() <= 0 && this->_internal_inr() >= 0)) {
    total_size += 1 + 4;
  }

  // float outL = 3;
  if (!(this->_internal_outl() <= 0 && this->_internal_outl() >= 0)) {
    total_size += 1 + 4;
  }

  // float outR = 4;
  if (!(this->_internal_outr() <= 0 && this->_internal_outr() >= 0)) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProcessorLiveData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ProcessorLiveData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProcessorLiveData::GetClassData() const { return &_class_data_; }

void ProcessorLiveData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ProcessorLiveData *>(to)->MergeFrom(
      static_cast<const ProcessorLiveData &>(from));
}


void ProcessorLiveData::MergeFrom(const ProcessorLiveData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fmsmoov.ProcessorLiveData)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from._internal_inl() <= 0 && from._internal_inl() >= 0)) {
    _internal_set_inl(from._internal_inl());
  }
  if (!(from._internal_inr() <= 0 && from._internal_inr() >= 0)) {
    _internal_set_inr(from._internal_inr());
  }
  if (!(from._internal_outl() <= 0 && from._internal_outl() >= 0)) {
    _internal_set_outl(from._internal_outl());
  }
  if (!(from._internal_outr() <= 0 && from._internal_outr() >= 0)) {
    _internal_set_outr(from._internal_outr());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessorLiveData::CopyFrom(const ProcessorLiveData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fmsmoov.ProcessorLiveData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessorLiveData::IsInitialized() const {
  return true;
}

void ProcessorLiveData::InternalSwap(ProcessorLiveData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProcessorLiveData, outr_)
      + sizeof(ProcessorLiveData::outr_)
      - PROTOBUF_FIELD_OFFSET(ProcessorLiveData, inl_)>(
          reinterpret_cast<char*>(&inl_),
          reinterpret_cast<char*>(&other->inl_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProcessorLiveData::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_fmsmoov_2eproto_getter, &descriptor_table_fmsmoov_2eproto_once,
      file_level_metadata_fmsmoov_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fmsmoov
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::fmsmoov::ProcessorLiveData* Arena::CreateMaybeMessage< ::fmsmoov::ProcessorLiveData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fmsmoov::ProcessorLiveData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
